### ISSUE TITLE
z3-solver package on Python package index doesn't include Python 3 wheels

### ISSUE THREAD

**Issue by jfinkels** [angr/angr-z3#7]
https://pypi.python.org/pypi/z3-solver

The `z3-solver` package only has Python 2 wheels, but I expect it to have Python 3 wheels as well, since the documentation seems to suggest that there is Python 3 support.

(I was directed here by https://github.com/Z3Prover/z3/issues/1254#issuecomment-329397358.)

**Comment by bannsec** [comment]
Actually came here to say something similar. Especially given i know angr is trying to move to be python 3, this will likely need to be added at some point.

**Comment by rhelmot** [comment]
New release has wheels marked py2+py3, and installation works well. I still haven't figured out the setuptools magic to do this automatically (last i checked it was `is_pure=True` but that hasn't done the trick) but luckily the metadata is purely in the name of the wheel so I can just... set it so
